/**
 * @file vite.content-ui.config.mjs
 * 文件职责：content-ui 独立 lib 构建——src/content-ui 打包为 classic IIFE，
 *   输出 extension/content-ui.js（生成物入库，与 design.js 同策略），
 *   manifest content_scripts 于 content.js 之前加载。
 * 主要内容：format=iife、name=RoamCatContentUI（暴露为全局对象）、
 *   始终 oxc minify（页面注入体积敏感，dev/release 产物一致）、
 *   writeBundle 写入 // Generated by 来源声明（R7 生成物豁免标记）。
 * 模块边界：只影响 content-ui 产物；页面 HTML 构建走 vite.config.mjs。
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.

 */
import {defineConfig} from 'vite';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const repoRoot = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(repoRoot, 'roamcat-0.0.1', 'extension', 'content-ui.js');
const banner = '// Generated by vite.content-ui.config.mjs from src/content-ui/index.js; do not edit by hand.\n';

export default defineConfig({
  plugins: [{
    name: 'content-ui-banner',
    writeBundle() {
      const source = fs.readFileSync(outFile, 'utf8');
      if (!source.startsWith('// Generated by')) fs.writeFileSync(outFile, banner + source);
    },
  }],
  build: {
    outDir: path.join(repoRoot, 'roamcat-0.0.1', 'extension'),
    emptyOutDir: false,
    sourcemap: false,
    minify: 'oxc',
    lib: {
      entry: path.join(repoRoot, 'src', 'content-ui', 'index.js'),
      name: 'RoamCatContentUI',
      formats: ['iife'],
      fileName: () => 'content-ui.js',
    },
  },
});
